# Handling Reading
encoding: "utf-8"

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
permalink:        /:categories/:title
relative_permalinks: true

# Setup
title:            Giquieu Duarte Pereira
tagline:          ''
description:      'desenvolvedor apaixonado pelo que faz'
# url:            ''
baseurl:          /

author:
  name:           'Giquieu Duarte Pereira'
  url:            https://twitter.com/giquieu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/giquieu
